sudo: required
language: node_js
node_js: "10.6.0"

script: skip

jobs:
  include:
    - stage: Lint
      script:
        - cd $TRAVIS_BUILD_DIR/client && npm install && npm run lint
        - cd $TRAVIS_BUILD_DIR/server && npm install && npm run lint

#    - stage: Audit
#      script:
#        - cd $TRAVIS_BUILD_DIR/client && npm audit --production
#        - cd $TRAVIS_BUILD_DIR/server && npm audit --production

    - stage: Tests
      script: echo "No tests at the moment"

    - stage: Build and push image
      services:
        - docker
      install: skip
      before_script:
        - docker build -t rupaya/scan-server -f Dockerfile.server .
        - docker build -t rupaya/scan-client -f Dockerfile.client .
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker tag rupaya/scan-server rupaya/scan-server:latest
        - docker push rupaya/scan-server:latest
        - docker tag rupaya/scan-server rupaya/scan-server:$TRAVIS_BUILD_ID
        - docker push rupaya/scan-server:$TRAVIS_BUILD_ID
        - docker tag rupaya/scan-client rupaya/scan-client:latest
        - docker push rupaya/scan-client:latest
        - docker tag rupaya/scan-client rupaya/scan-client:$TRAVIS_BUILD_ID
        - docker push rupaya/scan-client:$TRAVIS_BUILD_ID

    - stage: Build and push image (tagged)
      services:
        - docker
      install: skip
      before_script:
        - docker build -t rupaya/scan-server -f Dockerfile.server .
        - docker build -t rupaya/scan-client -f Dockerfile.client .
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker tag rupaya/scan-server rupaya/scan-server:latest
        - docker push rupaya/scan-server:latest
        - docker tag rupaya/scan-server rupaya/scan-server:testnet
        - docker push rupaya/scan-server:testnet
        - docker tag rupaya/scan-server rupaya/scan-server:$TRAVIS_TAG
        - docker push rupaya/scan-server:$TRAVIS_TAG
        - docker tag rupaya/scan-client rupaya/scan-client:latest
        - docker push rupaya/scan-client:latest
        - docker tag rupaya/scan-client rupaya/scan-client:testnet
        - docker push rupaya/scan-client:testnet
        - docker tag rupaya/scan-client rupaya/scan-client:$TRAVIS_TAG
        - docker push rupaya/scan-client:$TRAVIS_TAG

    - stage: Deploy in devnet
      install: skip
      before_script:
        - openssl enc -aes-256-cbc -d -in newTravis.pem.enc -K $encrypted_1abf86bccdee_key -iv $encrypted_1abf86bccdee_iv -out travis.pem
        - eval "$(ssh-agent -s)"
        - chmod 600 ./travis.pem
        - echo -e "Host $DEVNET_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - ssh-add ./travis.pem
      script:
        - ssh -i ./travis.pem -l $DEVNET_SSH_USER $DEVNET_SSH_IP docker service update --image rupaya/scan-client:latest devnet-main_scan 1> /dev/null
        - ssh -i ./travis.pem -l $DEVNET_SSH_USER $DEVNET_SSH_IP docker service update --image rupaya/scan-server:latest devnet-main_scan_crawler 1> /dev/null
        - ssh -i ./travis.pem -l $DEVNET_SSH_USER $DEVNET_SSH_IP docker service update --image rupaya/scan-server:latest devnet-main_scan_server 1> /dev/null
        - ssh -i ./travis.pem -l $DEVNET_SSH_USER $DEVNET_SSH_IP docker service update --image rupaya/scan-server:latest devnet-main_scan_producer 1> /dev/null
      after_success:
        -  'curl -X POST --data-urlencode "payload={\"channel\": \"#deployments\", \"username\": \"Travis\", \"attachments\":[{\"fallback\":\"[devnet] Deployment succeeded\",\"pretext\":\"\",\"color\":\"good\",\"fields\":[{\"title\":\"[devnet] scan\",\"value\":\"Deployment succeeded.\",\"short\":true}]}], \"icon_emoji\": \":male-construction-worker:\"}" $SLACK_DEPLOY_URL'
      after_failure:
        -  'curl -X POST --data-urlencode "payload={\"channel\": \"#deployments\", \"username\": \"Travis\", \"attachments\":[{\"fallback\":\"[devnet] Deployment failed\",\"pretext\":\"\",\"color\":\"danger\",\"fields\":[{\"title\":\"[devnet] scan\",\"value\":\"Deployment failed.\",\"short\":false}]}], \"icon_emoji\": \":male-construction-worker:\"}" $SLACK_DEPLOY_URL'

    - stage: Deploy in testnet
      install: skip
      before_script:
        - openssl enc -aes-256-cbc -d -in newTravis.pem.enc -K $encrypted_1abf86bccdee_key -iv $encrypted_1abf86bccdee_iv -out travis.pem
        - eval "$(ssh-agent -s)"
        - chmod 600 ./travis.pem
        - echo -e "Host $TESTNET_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - ssh-add ./travis.pem
      script:
        - ssh -i ./travis.pem -l $TESTNET_SSH_USER $TESTNET_SSH_IP docker service update --image rupaya/scan-client:testnet testnet_scan 1> /dev/null
        - ssh -i ./travis.pem -l $TESTNET_SSH_USER $TESTNET_SSH_IP docker service update --image rupaya/scan-server:testnet testnet_scan_crawler 1> /dev/null
        - ssh -i ./travis.pem -l $TESTNET_SSH_USER $TESTNET_SSH_IP docker service update --image rupaya/scan-server:testnet testnet_scan_server 1> /dev/null
        - ssh -i ./travis.pem -l $TESTNET_SSH_USER $TESTNET_SSH_IP docker service update --image rupaya/scan-server:testnet testnet_scan_producer 1> /dev/null
      after_success:
        -  'curl -X POST --data-urlencode "payload={\"channel\": \"#deployments\", \"username\": \"Travis\", \"attachments\":[{\"fallback\":\"[testnet] Deployment succeeded\",\"pretext\":\"\",\"color\":\"good\",\"fields\":[{\"title\":\"[testnet] scan\",\"value\":\"Deployment succeeded.\",\"short\":true}]}], \"icon_emoji\": \":male-construction-worker:\"}" $SLACK_DEPLOY_URL'
      after_failure:
        -  'curl -X POST --data-urlencode "payload={\"channel\": \"#deployments\", \"username\": \"Travis\", \"attachments\":[{\"fallback\":\"[testnet] Deployment failed\",\"pretext\":\"\",\"color\":\"danger\",\"fields\":[{\"title\":\"[testnet] scan\",\"value\":\"Deployment failed.\",\"short\":false}]}], \"icon_emoji\": \":male-construction-worker:\"}" $SLACK_DEPLOY_URL'

stages:
  - name: Lint
#  - name: Audit
  - name: Tests
  - name: Build and push image
    if: type != pull_request AND branch = master AND tag IS blank AND repo = rupaya/scan
  - name: Build and push image (tagged)
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = rupaya/scan
#  - name: Deploy in devnet
#    if: type != pull_request AND branch = master AND repo = rupaya/scan
  - name: Deploy in testnet
    if: type != pull_request AND branch = master AND repo = rupaya/scan
#    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = rupaya/scan
